### ISSUE TITLE
Bi-encoder 모델 훈련된 가중치 데이터

### ISSUE THREAD

**Issue by ByungjunKim** [lih0905/WSD_kor#1]
안녕하세요. 좋은 모듈 만들어주셔서 감사합니다.
제가 연구용으로 한번 활용해보려하는데요.
"Bi-encoder 모델 훈련된 가중치 데이터" 구글 드라이브 링크가 깨져있어서요.
이걸 다운 받을 수 있을까요? 그리고 해당 가중치 데이터가 있어야 온전히 돌아가는지요?

감사합니다.

**Comment by lih0905** [comment]
안녕하세요, 답변이 늦었습니다. 
확인해보니 구글 드라이브 용량 확보한다고 얼마전에 삭제해버렸네요 ㅜㅜ
하드디스크에 백업해둔 것으로 기억했는데 찾아보니 그것도 없어서 아무래도 현재는 체크포인트 파일을 찾기가 어려울 것 같습니다.
본문 내용은 수정해두겠습니다.

체크포인트 파일이 없으니 직접 훈련시키셔야할 것 같은데,
저도 한참 전에 했던 작업이라 동일한 결과가 나올지 확인하기가 조금 어렵네요.
무튼 좋은 결과 얻으시길 바랍니다.

**Comment by ByungjunKim** [comment]
답변 감사합니다!
